name: Build and Deploy — Mac
run-name: ${{ github.actor }} is building a Mac release

on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  deploy-on-mac:
    runs-on: macos-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - uses: apple-actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.MACOS_CERTIFICATE }}
          p12-password: ${{ secrets.MACOS_CERTIFICATE_PWD }}

      - name: Build and deploy on Mac
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          appleId: ${{ secrets.APPLE_ID }}
          appleIdPassword: ${{ secrets.APPLE_PASSWORD }}
        run: npm run build -- --desktop --publish
